apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-static-route-controller
  namespace: kube-system
  labels:
    app: node-static-route-controller
spec:
  selector:
    matchLabels:
      app: node-static-route-controller
  template:
    metadata:
      labels:
        app: node-static-route-controller
    spec:
      hostNetwork: true
      containers:
        - name: node-static-route-controller
          image: stwalkerster/kube-node-static-route:latest
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
